---
title: "Calibration of rsofun with Phydro"
author: "Jaideep Joshi"
date: "2023-09-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(reshape2)
library(rsofun)
```

## Generate data if not already available

```{r}
site <- "GF-Guy"
```

```{r}
load(paste0("../data/",site,"_p_hydro_drivers.rda"))
load(paste0("../data/",site,"_p_hydro_validation.rda"))

p_hydro_drivers$forcing[[1]]$netrad[is.na(p_hydro_drivers$forcing[[1]]$netrad)] = 0
p_hydro_drivers$forcing[[1]]$patm[p_hydro_drivers$forcing[[1]]$patm < 0] = 1.0135e5

```

Function to quickly run model and plot outputs

```{r}

plot_pmodel = function(params_modl){
  output_p <- rsofun::runread_pmodel_f(
    p_hydro_drivers,
    par = params_modl
  )
  
  output_p$data[[1]] %>% select(date, gpp, latenth) %>% 
    rename(le = latenth) %>% 
    melt("date") %>% 
    mutate(group="model") %>% 
    rbind(p_hydro_validation$data[[1]] %>% 
            select(date, gpp, le) %>%
            mutate(gpp = gpp*86400/1e6*12) %>% # convert to gC m-2 day-1
            mutate(le = le*86400) %>%  # convert W m-2 to J m-2 day-1 
            melt("date") %>% 
            mutate(group="obs")) %>% 
    ggplot(aes(y=value, x=as.Date(date))) +
    geom_line(aes(group=group, col=group), alpha=0.7) +
    theme_classic() +
    theme(strip.background = element_rect(color = "white", size = 1))+
    facet_wrap(~variable, scales = "free", nrow = 2)
}
```

```{r}
params_modl <- list(
  kphio              = 0.089, # 0.11, #0.04998,    
  kphio_par_a        = 0.0,        # set to zero to disable temperature-dependence of kphio
  kphio_par_b        = 1.0,
  soilm_thetastar    = 0.6 * 240,  # to recover old setup with soil moisture stress
  soilm_betao        = 0.0,
  beta_unitcostratio = 146.0,
  rd_to_vcmax        = 0.014,      # value from Atkin et al. 2015 for C3 herbaceous
  tau_acclim         = 30.0,
  kc_jmax            = 0.41,
  phydro_K_plant     = 0.3e-16,
  phydro_p50_plant   = -1,
  phydro_b_plant     = 1,
  phydro_alpha       = 0.1,
  phydro_gamma       = 1,
  bsoil              = 3,
  whc                = 90
)
```

## Model calibration

### P-model calibration (GenSA)

```{r}
p_hydro_drivers$params_siml[[1]]$use_phydro = F
p_hydro_drivers$params_siml[[1]]$use_pml = F

# Define calibration settings and parameter ranges from previous work
settings_rmse <- list(
  method = 'GenSA',                   # minimizes the RMSE
  metric = cost_rmse_pmodel,          # our cost function
  control = list(                     # control parameters for optimizer GenSA
    maxit = 100),                     
  par = list(                         # bounds for the parameter space
    kphio = list(lower=0.02, upper=0.2, init=0.05)
  ),
  parallel = T,
  ncores = 8
)

# Calibrate the model and optimize the free parameters using
# demo datasets
pars_calib_rmse <- calib_sofun(
  # calib_sofun arguments:
  drivers = p_hydro_drivers,  
  obs = p_hydro_validation,
  settings = settings_rmse,
  # extra arguments passed to the cost function:
  par_fixed = list(         # fix all other parameters
    kphio_par_a        = 0.0,        # set to zero to disable temperature-dependence 
    # of kphio, setup ORG
    kphio_par_b        = 1.0,
    soilm_thetastar    = 0.6 * 240,  # to recover paper setup with soil moisture stress
    soilm_betao        = 0.0,
    beta_unitcostratio = 146.0,
    rd_to_vcmax        = 0.014,      # value from Atkin et al. 2015 for C3 herbaceous
    tau_acclim         = 30.0,
    kc_jmax            = 0.41,
    whc                = 90
  ),
  targets = "gpp"           # define target variable GPP
)

print(pars_calib_rmse)

params_modl_opt = params_modl
params_modl_opt$kphio = pars_calib_rmse$par
plot_pmodel(params_modl_opt)

```

### P-model calibration (BayesianTools)

```{r}
p_hydro_drivers$params_siml[[1]]$use_phydro = F
p_hydro_drivers$params_siml[[1]]$use_pml = F

# Define calibration settings and parameter ranges from previous work
settings_bayes <- list(
  method = "BayesianTools",
  par = list(
    kphio = list(lower=0.04, upper=0.09, init=0.05),
    err_gpp = list(lower = 0.01, upper = 4, init = 2)
  ),
  metric = rsofun::cost_likelihood_pmodel,
  control = list(
    sampler = "DEzs",
    settings = list(
      nrChains = 1,
      burnin = 500,        
      iterations = 600     # kept artificially low
    )
  )
)

# Calibrate the model and optimize the free parameters using
# demo datasets
pars_calib_bayes <- calib_sofun(
  # calib_sofun arguments:
  drivers = p_hydro_drivers,  
  obs = p_hydro_validation,
  settings = settings_bayes,
  # extra arguments passed to the cost function:
  par_fixed = list(         # fix all other parameters
    kphio_par_a        = 0.0,        # set to zero to disable temperature-dependence 
    # of kphio, setup ORG
    kphio_par_b        = 1.0,
    soilm_thetastar    = 0.6 * 240,  # to recover paper setup with soil moisture stress
    soilm_betao        = 0.0,
    beta_unitcostratio = 146.0,
    rd_to_vcmax        = 0.014,      # value from Atkin et al. 2015 for C3 herbaceous
    tau_acclim         = 30.0,
    kc_jmax            = 0.41,
    whc                = 90
  ),
  targets = "gpp"           # define target variable GPP
)

print(pars_calib_bayes)

params_modl_opt = params_modl
params_modl_opt$kphio = pars_calib_bayes$par[["kphio"]]
plot_pmodel(params_modl_opt)

```
