#' Run SOFUN and read output
#'
#' Runs the model and reads output in once.
#'
#' @param settings A named list containing the simulation settings (see vignette_rsofun.pdf for more information and examples).
#' @param ddf_input A data frame containing the model forcing for each model time step. 
#' @param makecheck A logical specifying whether checks are performed to verify forcings.
#'
#' @return Returns a named list of data frames (tibbles) containing model outputs (separate data frames for 
#' each site, with columns for the different model output variables). Note that outputs generated by the
#' \code{"lonlat"} model setup are not read into R and not returned by \code{runread_sofun()} due to excessive
#' memory requirements. 
#' @export
#'
#' @examples mod <- runread_sofun( settings = settings, setup = setup_sofun )
#' 
runread_sofun_f <- function( settings, ddf_input, list_soiltexture, params_modl, makecheck = TRUE ){

  ddf <- purrr::map(
    as.list(settings$sitename),
    ~run_sofun_f_bysite( 
      settings         = dplyr::filter(settings, sitename == .), 
      params_modl      = params_modl, 
      list_soiltexture = list_soiltexture,
      forcing          = dplyr::filter(ddf_input, sitename == .),
      makecheck        = makecheck  
    )
  )
  names(ddf) <- settings$sitename
  # ddf <- ddf %>% dplyr::bind_rows(.id = "sitename")
  out <- list(daily = ddf)
  return(out)
}
