#' Run SOFUN and read output
#'
#' Runs the model and reads output in once.
#'
#' @param df_drivers
#' @param params_modl
#' @param makecheck A logical specifying whether checks are performed to verify forcings.
#'
#' @return Returns a named list of data frames (tibbles) containing model outputs (separate data frames for 
#' each site, with columns for the different model output variables). Note that outputs generated by the
#' \code{"lonlat"} model setup are not read into R and not returned by \code{runread_sofun()} due to excessive
#' memory requirements. 
#' @export
#'
#' @examples mod <- runread_sofun( settings = settings, setup = setup_sofun )
#' 
runread_sofun_f <- function( df_drivers, params_modl, makecheck = TRUE ){

  # if (parallelise){
  #   
  # 
  #   
  #   ## set up the cluster
  #   cluster <- multidplyr::new_cluster(settings$ncores)
  #   
  #   ## distribute to to cores, making sure all data from a specific site is sent to the same core
  #   forcing_distr <- forcing %>% 
  #     dplyr::group_by(sitename) %>% 
  #     multidplyr::partition(cluster)
  #   
  # }
  
  df_out <- df_drivers %>% 
    mutate(out_sofun = purrr::pmap(
      .,
      run_sofun_f_bysite,
      params_modl = params_modl,
      makecheck = makecheck
    )) %>% 
    dplyr::select(sitename, out_sofun)
  
  # ddf <- purrr::map(
  #   as.list(settings$sitename),
  #   ~run_sofun_f_bysite( 
  #     settings         = dplyr::filter(settings, sitename == .), 
  #     params_modl      = params_modl, 
  #     df_soiltexture = df_soiltexture,
  #     forcing          = dplyr::filter(forcing, sitename == .),
  #     makecheck        = makecheck  
  #   )
  # )
  # names(ddf) <- settings$sitename
  # # ddf <- ddf %>% dplyr::bind_rows(.id = "sitename")
  # out <- list(daily = ddf)
  
  return(df_out)
}
