---
title: "Get soil moisture data for Keith"
author: "Beni Stocker"
date: "9/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lubridate)
library(rsofun)
library(purrr)
library(readr)
```

## Collect data

Collect data from the latest simulations with variable soil water holding capacity.
```{r}
settings_sims <- list(
  siteinfo        = rsofun::metainfo_Tier1_sites_kgclimate_fluxnet2015,
  ensemble        = TRUE,
  setup           = "site",
  name            = "fluxnet2015",
  dir_sofun       = "/alphadata01/bstocker/sofun/trunk/",
  path_input      = "/alphadata01/bstocker/sofun/input_fluxnet2015_sofun_TEST/",
  path_output     = "~/sofun/output_pet_fluxnet2015_sofun/v2/",
  path_output_nc  = "~/sofun/output_nc_pet_fluxnet2015_sofun/v2/",
  grid            = NA,
  implementation  = "fortran",
  in_ppfd         = TRUE,
  in_netrad       = FALSE,
  recycle         = 1,
  spinupyears     = 10,
  soilmstress     = TRUE,
  tempstress      = TRUE,
  loutdgpp        = FALSE,
  loutdwcont      = TRUE,
  loutdaet        = FALSE,
  loutdpet        = FALSE,
  loutdalpha      = FALSE
  )

setup_sofun <- list(
  model      = "pmodel",
  dir        = "/alphadata01/bstocker/sofun/trunk",
  do_compile = FALSE,
  simsuite   = FALSE
  )

settings_sims <- prepare_setup_sofun( 
    settings = settings_sims,
    setup = setup_sofun,
    write_paramfils = FALSE 
    )

## read from NetCDF outputs
ddf_list <- read_sofun( 
  settings = settings_sims, 
  setup = setup_sofun 
  )

## re-structure data
df <- ddf_list$daily %>% 
  bind_rows(.id = "site")

## now, 'wcont' is in units of mm. Convert to fraction of water 
## holding capacity by division by max WHC from site meta info
df <- df %>% 
  left_join(rsofun::metainfo_Tier1_sites_kgclimate_fluxnet2015 %>% select(site = sitename, whc), by = "site") %>% 
  rowwise() %>% 
  mutate(wfrac = wcont / whc)

## Complement with observed soil moisture, read from FLUXNET files
getvars <- c()
df_fluxnet <- purrr::map( 
  as.list(settings_sims$sitenames),
  ~get_obs_bysite_fluxnet2015( 
    sitename = ., 
    path_fluxnet2015 = "/alphadata01/bstocker/data/FLUXNET-2015_Tier1/20160128/point-scale_none_1d/original/unpacked/", 
    path_fluxnet2015_hh = "/alphadata01/bstocker/data/FLUXNET-2015_Tier1/20160128/point-scale_none_0.5h/original/unpacked/",
    timescale = "d", 
    getvars = getvars, 
    getswc = TRUE,                              
    verbose = TRUE,
    threshold_SWC = 0.8,  ## at least 80% of data is not gap-filled
    return_qc = FALSE
    ) ) %>% 
  setNames(settings_sims$sitenames) %>% 
  bind_rows( .id = "sitename" ) %>% 
  dplyr::rename(site = sitename)
  
## combine the two
df <- df %>% 
  left_join(df_fluxnet, by = c("site", "date"))

write_csv(df, path = "/alphadata01/bstocker/rsofun/data/df_fluxnet2015_soilm_for_keith.csv")
```

